// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: auction.proto

package auction_api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAuctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      int64                  `protobuf:"varint,1,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	StartPrice    int64                  `protobuf:"varint,2,opt,name=start_price,json=startPrice,proto3" json:"start_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuctionRequest) Reset() {
	*x = CreateAuctionRequest{}
	mi := &file_auction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuctionRequest) ProtoMessage() {}

func (x *CreateAuctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuctionRequest.ProtoReflect.Descriptor instead.
func (*CreateAuctionRequest) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAuctionRequest) GetObjectId() int64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *CreateAuctionRequest) GetStartPrice() int64 {
	if x != nil {
		return x.StartPrice
	}
	return 0
}

type CreateAuctionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     int64                  `protobuf:"varint,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Artist        string                 `protobuf:"bytes,3,opt,name=artist,proto3" json:"artist,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuctionResponse) Reset() {
	*x = CreateAuctionResponse{}
	mi := &file_auction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuctionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuctionResponse) ProtoMessage() {}

func (x *CreateAuctionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuctionResponse.ProtoReflect.Descriptor instead.
func (*CreateAuctionResponse) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAuctionResponse) GetAuctionId() int64 {
	if x != nil {
		return x.AuctionId
	}
	return 0
}

func (x *CreateAuctionResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateAuctionResponse) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *CreateAuctionResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type ListAuctionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuctionsRequest) Reset() {
	*x = ListAuctionsRequest{}
	mi := &file_auction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuctionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuctionsRequest) ProtoMessage() {}

func (x *ListAuctionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuctionsRequest.ProtoReflect.Descriptor instead.
func (*ListAuctionsRequest) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{2}
}

func (x *ListAuctionsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAuctionsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Auction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Artist        string                 `protobuf:"bytes,3,opt,name=artist,proto3" json:"artist,omitempty"`
	CurrentPrice  int64                  `protobuf:"varint,4,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auction) Reset() {
	*x = Auction{}
	mi := &file_auction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auction) ProtoMessage() {}

func (x *Auction) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auction.ProtoReflect.Descriptor instead.
func (*Auction) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{3}
}

func (x *Auction) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Auction) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Auction) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *Auction) GetCurrentPrice() int64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *Auction) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type ListAuctionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auctions      []*Auction             `protobuf:"bytes,1,rep,name=auctions,proto3" json:"auctions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuctionsResponse) Reset() {
	*x = ListAuctionsResponse{}
	mi := &file_auction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuctionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuctionsResponse) ProtoMessage() {}

func (x *ListAuctionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuctionsResponse.ProtoReflect.Descriptor instead.
func (*ListAuctionsResponse) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{4}
}

func (x *ListAuctionsResponse) GetAuctions() []*Auction {
	if x != nil {
		return x.Auctions
	}
	return nil
}

var File_auction_proto protoreflect.FileDescriptor

const file_auction_proto_rawDesc = "" +
	"\n" +
	"\rauction.proto\x12\vauction_api\x1a\x1cgoogle/api/annotations.proto\"T\n" +
	"\x14CreateAuctionRequest\x12\x1b\n" +
	"\tobject_id\x18\x01 \x01(\x03R\bobjectId\x12\x1f\n" +
	"\vstart_price\x18\x02 \x01(\x03R\n" +
	"startPrice\"\x81\x01\n" +
	"\x15CreateAuctionResponse\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\x03R\tauctionId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x03 \x01(\tR\x06artist\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\"C\n" +
	"\x13ListAuctionsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"\x89\x01\n" +
	"\aAuction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x03 \x01(\tR\x06artist\x12#\n" +
	"\rcurrent_price\x18\x04 \x01(\x03R\fcurrentPrice\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\"H\n" +
	"\x14ListAuctionsResponse\x120\n" +
	"\bauctions\x18\x01 \x03(\v2\x14.auction_api.AuctionR\bauctions2\xec\x01\n" +
	"\x0eAuctionService\x12o\n" +
	"\rCreateAuction\x12!.auction_api.CreateAuctionRequest\x1a\".auction_api.CreateAuctionResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/auctions\x12i\n" +
	"\fListAuctions\x12 .auction_api.ListAuctionsRequest\x1a!.auction_api.ListAuctionsResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/auctionsBAZ?github.com/students-api/bidding-service/internal/pb/auction_apib\x06proto3"

var (
	file_auction_proto_rawDescOnce sync.Once
	file_auction_proto_rawDescData []byte
)

func file_auction_proto_rawDescGZIP() []byte {
	file_auction_proto_rawDescOnce.Do(func() {
		file_auction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auction_proto_rawDesc), len(file_auction_proto_rawDesc)))
	})
	return file_auction_proto_rawDescData
}

var file_auction_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_auction_proto_goTypes = []any{
	(*CreateAuctionRequest)(nil),  // 0: auction_api.CreateAuctionRequest
	(*CreateAuctionResponse)(nil), // 1: auction_api.CreateAuctionResponse
	(*ListAuctionsRequest)(nil),   // 2: auction_api.ListAuctionsRequest
	(*Auction)(nil),               // 3: auction_api.Auction
	(*ListAuctionsResponse)(nil),  // 4: auction_api.ListAuctionsResponse
}
var file_auction_proto_depIdxs = []int32{
	3, // 0: auction_api.ListAuctionsResponse.auctions:type_name -> auction_api.Auction
	0, // 1: auction_api.AuctionService.CreateAuction:input_type -> auction_api.CreateAuctionRequest
	2, // 2: auction_api.AuctionService.ListAuctions:input_type -> auction_api.ListAuctionsRequest
	1, // 3: auction_api.AuctionService.CreateAuction:output_type -> auction_api.CreateAuctionResponse
	4, // 4: auction_api.AuctionService.ListAuctions:output_type -> auction_api.ListAuctionsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_auction_proto_init() }
func file_auction_proto_init() {
	if File_auction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auction_proto_rawDesc), len(file_auction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auction_proto_goTypes,
		DependencyIndexes: file_auction_proto_depIdxs,
		MessageInfos:      file_auction_proto_msgTypes,
	}.Build()
	File_auction_proto = out.File
	file_auction_proto_goTypes = nil
	file_auction_proto_depIdxs = nil
}
