// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/students-api/bidding-service/internal/models"
)

// BidRepository is an autogenerated mock type for the BidRepository type
type BidRepository struct {
	mock.Mock
}

// CreateBid provides a mock function with given fields: ctx, bid
func (_m *BidRepository) CreateBid(ctx context.Context, bid models.Bid) error {
	ret := _m.Called(ctx, bid)

	if len(ret) == 0 {
		panic("no return value specified for CreateBid")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Bid) error); ok {
		r0 = rf(ctx, bid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBidRepository creates a new instance of BidRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBidRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BidRepository {
	mock := &BidRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
