// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	kafka "github.com/students-api/bidding-service/internal/broker/kafka"
)

// EventSender is an autogenerated mock type for the EventSender type
type EventSender struct {
	mock.Mock
}

// SendBidPlaced provides a mock function with given fields: event
func (_m *EventSender) SendBidPlaced(event kafka.BidEvent) error {
	ret := _m.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for SendBidPlaced")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(kafka.BidEvent) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEventSender creates a new instance of EventSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventSender {
	mock := &EventSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
