// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// LockService is an autogenerated mock type for the LockService type
type LockService struct {
	mock.Mock
}

// AcquireLock provides a mock function with given fields: ctx, auctionID
func (_m *LockService) AcquireLock(ctx context.Context, auctionID int64) (bool, error) {
	ret := _m.Called(ctx, auctionID)

	if len(ret) == 0 {
		panic("no return value specified for AcquireLock")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (bool, error)); ok {
		return rf(ctx, auctionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = rf(ctx, auctionID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, auctionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReleaseLock provides a mock function with given fields: ctx, auctionID
func (_m *LockService) ReleaseLock(ctx context.Context, auctionID int64) error {
	ret := _m.Called(ctx, auctionID)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseLock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, auctionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLockService creates a new instance of LockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LockService {
	mock := &LockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
