// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: bidding.proto

package bidding_api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaceBidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     int64                  `protobuf:"varint,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceBidRequest) Reset() {
	*x = PlaceBidRequest{}
	mi := &file_bidding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBidRequest) ProtoMessage() {}

func (x *PlaceBidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bidding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBidRequest.ProtoReflect.Descriptor instead.
func (*PlaceBidRequest) Descriptor() ([]byte, []int) {
	return file_bidding_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceBidRequest) GetAuctionId() int64 {
	if x != nil {
		return x.AuctionId
	}
	return 0
}

func (x *PlaceBidRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PlaceBidRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PlaceBidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceBidResponse) Reset() {
	*x = PlaceBidResponse{}
	mi := &file_bidding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBidResponse) ProtoMessage() {}

func (x *PlaceBidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bidding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBidResponse.ProtoReflect.Descriptor instead.
func (*PlaceBidResponse) Descriptor() ([]byte, []int) {
	return file_bidding_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceBidResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PlaceBidResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAuctionStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     int64                  `protobuf:"varint,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuctionStateRequest) Reset() {
	*x = GetAuctionStateRequest{}
	mi := &file_bidding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuctionStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuctionStateRequest) ProtoMessage() {}

func (x *GetAuctionStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bidding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuctionStateRequest.ProtoReflect.Descriptor instead.
func (*GetAuctionStateRequest) Descriptor() ([]byte, []int) {
	return file_bidding_proto_rawDescGZIP(), []int{2}
}

func (x *GetAuctionStateRequest) GetAuctionId() int64 {
	if x != nil {
		return x.AuctionId
	}
	return 0
}

type GetAuctionStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentMaxBid int64                  `protobuf:"varint,1,opt,name=current_max_bid,json=currentMaxBid,proto3" json:"current_max_bid,omitempty"`
	WinnerId      int64                  `protobuf:"varint,2,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuctionStateResponse) Reset() {
	*x = GetAuctionStateResponse{}
	mi := &file_bidding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuctionStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuctionStateResponse) ProtoMessage() {}

func (x *GetAuctionStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bidding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuctionStateResponse.ProtoReflect.Descriptor instead.
func (*GetAuctionStateResponse) Descriptor() ([]byte, []int) {
	return file_bidding_proto_rawDescGZIP(), []int{3}
}

func (x *GetAuctionStateResponse) GetCurrentMaxBid() int64 {
	if x != nil {
		return x.CurrentMaxBid
	}
	return 0
}

func (x *GetAuctionStateResponse) GetWinnerId() int64 {
	if x != nil {
		return x.WinnerId
	}
	return 0
}

var File_bidding_proto protoreflect.FileDescriptor

const file_bidding_proto_rawDesc = "" +
	"\n" +
	"\rbidding.proto\x12\vbidding_api\x1a\x1cgoogle/api/annotations.proto\"a\n" +
	"\x0fPlaceBidRequest\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\x03R\tauctionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"F\n" +
	"\x10PlaceBidResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"7\n" +
	"\x16GetAuctionStateRequest\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\x03R\tauctionId\"^\n" +
	"\x17GetAuctionStateResponse\x12&\n" +
	"\x0fcurrent_max_bid\x18\x01 \x01(\x03R\rcurrentMaxBid\x12\x1b\n" +
	"\twinner_id\x18\x02 \x01(\x03R\bwinnerId2\xf6\x01\n" +
	"\x0eBiddingService\x12\\\n" +
	"\bPlaceBid\x12\x1c.bidding_api.PlaceBidRequest\x1a\x1d.bidding_api.PlaceBidResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/bids\x12\x85\x01\n" +
	"\x0fGetAuctionState\x12#.bidding_api.GetAuctionStateRequest\x1a$.bidding_api.GetAuctionStateResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/auctions/{auction_id}/stateBAZ?github.com/students-api/bidding-service/internal/pb/bidding_apib\x06proto3"

var (
	file_bidding_proto_rawDescOnce sync.Once
	file_bidding_proto_rawDescData []byte
)

func file_bidding_proto_rawDescGZIP() []byte {
	file_bidding_proto_rawDescOnce.Do(func() {
		file_bidding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bidding_proto_rawDesc), len(file_bidding_proto_rawDesc)))
	})
	return file_bidding_proto_rawDescData
}

var file_bidding_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bidding_proto_goTypes = []any{
	(*PlaceBidRequest)(nil),         // 0: bidding_api.PlaceBidRequest
	(*PlaceBidResponse)(nil),        // 1: bidding_api.PlaceBidResponse
	(*GetAuctionStateRequest)(nil),  // 2: bidding_api.GetAuctionStateRequest
	(*GetAuctionStateResponse)(nil), // 3: bidding_api.GetAuctionStateResponse
}
var file_bidding_proto_depIdxs = []int32{
	0, // 0: bidding_api.BiddingService.PlaceBid:input_type -> bidding_api.PlaceBidRequest
	2, // 1: bidding_api.BiddingService.GetAuctionState:input_type -> bidding_api.GetAuctionStateRequest
	1, // 2: bidding_api.BiddingService.PlaceBid:output_type -> bidding_api.PlaceBidResponse
	3, // 3: bidding_api.BiddingService.GetAuctionState:output_type -> bidding_api.GetAuctionStateResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bidding_proto_init() }
func file_bidding_proto_init() {
	if File_bidding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bidding_proto_rawDesc), len(file_bidding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bidding_proto_goTypes,
		DependencyIndexes: file_bidding_proto_depIdxs,
		MessageInfos:      file_bidding_proto_msgTypes,
	}.Build()
	File_bidding_proto = out.File
	file_bidding_proto_goTypes = nil
	file_bidding_proto_depIdxs = nil
}
