// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: bidding.proto

package bidding_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BiddingServiceClient is the client API for BiddingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BiddingServiceClient interface {
	// Попробовать сделать ставку
	PlaceBid(ctx context.Context, in *PlaceBidRequest, opts ...grpc.CallOption) (*PlaceBidResponse, error)
	GetAuctionState(ctx context.Context, in *GetAuctionStateRequest, opts ...grpc.CallOption) (*GetAuctionStateResponse, error)
}

type biddingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBiddingServiceClient(cc grpc.ClientConnInterface) BiddingServiceClient {
	return &biddingServiceClient{cc}
}

func (c *biddingServiceClient) PlaceBid(ctx context.Context, in *PlaceBidRequest, opts ...grpc.CallOption) (*PlaceBidResponse, error) {
	out := new(PlaceBidResponse)
	err := c.cc.Invoke(ctx, "/bidding_api.BiddingService/PlaceBid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *biddingServiceClient) GetAuctionState(ctx context.Context, in *GetAuctionStateRequest, opts ...grpc.CallOption) (*GetAuctionStateResponse, error) {
	out := new(GetAuctionStateResponse)
	err := c.cc.Invoke(ctx, "/bidding_api.BiddingService/GetAuctionState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BiddingServiceServer is the server API for BiddingService service.
// All implementations must embed UnimplementedBiddingServiceServer
// for forward compatibility
type BiddingServiceServer interface {
	// Попробовать сделать ставку
	PlaceBid(context.Context, *PlaceBidRequest) (*PlaceBidResponse, error)
	GetAuctionState(context.Context, *GetAuctionStateRequest) (*GetAuctionStateResponse, error)
	mustEmbedUnimplementedBiddingServiceServer()
}

// UnimplementedBiddingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBiddingServiceServer struct {
}

func (UnimplementedBiddingServiceServer) PlaceBid(context.Context, *PlaceBidRequest) (*PlaceBidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceBid not implemented")
}
func (UnimplementedBiddingServiceServer) GetAuctionState(context.Context, *GetAuctionStateRequest) (*GetAuctionStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuctionState not implemented")
}
func (UnimplementedBiddingServiceServer) mustEmbedUnimplementedBiddingServiceServer() {}

// UnsafeBiddingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BiddingServiceServer will
// result in compilation errors.
type UnsafeBiddingServiceServer interface {
	mustEmbedUnimplementedBiddingServiceServer()
}

func RegisterBiddingServiceServer(s grpc.ServiceRegistrar, srv BiddingServiceServer) {
	s.RegisterService(&BiddingService_ServiceDesc, srv)
}

func _BiddingService_PlaceBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceBidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BiddingServiceServer).PlaceBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bidding_api.BiddingService/PlaceBid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BiddingServiceServer).PlaceBid(ctx, req.(*PlaceBidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BiddingService_GetAuctionState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuctionStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BiddingServiceServer).GetAuctionState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bidding_api.BiddingService/GetAuctionState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BiddingServiceServer).GetAuctionState(ctx, req.(*GetAuctionStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BiddingService_ServiceDesc is the grpc.ServiceDesc for BiddingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BiddingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bidding_api.BiddingService",
	HandlerType: (*BiddingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlaceBid",
			Handler:    _BiddingService_PlaceBid_Handler,
		},
		{
			MethodName: "GetAuctionState",
			Handler:    _BiddingService_GetAuctionState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bidding.proto",
}
